version: "3.7"

services:
  primary-node:
    build: ./
    command: >
      bash -c "/user/nrtsearch/build/install/nrtsearch/bin/lucene-server /user/nrtsearch/nrtsearch-primary-config.yaml"
    hostname: primary-node
    ports:
      - "8000:8000"

  replica-node:
    build: ./
    command: ./entrypoint_replica.sh
    deploy:
      replicas: 2
    hostname: replica-node
    ports:
      - "8001-8002:8000"
